from PyQt5.QtCore import Qt

COLOR_PAYMENT_FINISHED = 0xff92D050
COLOR_PAYMENT_PENDING = 0xffFF0000

COLOR_PRIORITY_LOW = 0xffAABF00
COLOR_PRIORITY_MEDIUM = 0xffFFFF00
COLOR_PRIORITY_HIGH = 0xffFFFF00

COLOR_ARRIVAL_PENDING = 0xffFF0000
COLOR_ARRIVAL_PARTIAL = 0xffFF6262
COLOR_ARRIVAL_RECLAIM = 0xffFF0000

RoleNodeId = Qt.UserRole + 1
# RoleStatus = Qt.UserRole + 2
# RoleAuthor = Qt.UserRole + 3
# RoleActive = Qt.UserRole + 4
